name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libglew-dev libglfw3-dev libglm-dev

    - name: Install Google Test dependencies
      run: sudo apt-get install -y libgtest-dev cmake
      
    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure
