name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libglew-dev libglfw3-dev libglm-dev gfortran freeglut3-dev
        pwd

    - name: Print working directory  before Google Build
      run: pwd

    - name: Build Google Test
      run: |
        mkdir -p build/googletest
        cd build/googletest
        pwd
        cmake ../../extern/googletest
        cmake --build .

    - name: Configure CMake
      run: |
        cmake -S . -B build
        pwd

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure
