name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print working directory after checkout
      run: | 
        pwd
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
        ls ${{ github.workspace }}

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Print working directory after CMake setup
      run: |
        pwd
        ls ${{ github.workspace }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglew-dev libglfw3-dev libglm-dev gfortran
        pwd
        ls ${{ github.workspace }}

    - name: Build Google Test
      run: |
        mkdir -p build/googletest
        echo "Listing github workspace"
        ls ${{ github.workspace }}
        echo "listing what is inside build/googletest"
        ls build/googletest
        cd build/googletest
        pwd
        echo "listing what is in ../../extern/googletest"
        ls ../../extern/googletest
        echo "Current directory"
        pwd
        cmake ../../extern/googletest
        cmake --build .

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Print working directory after configuring CMake
      run: pwd

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        pwd
        ctest --output-on-failure
