name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: .

    - name: Print working directory after checkout
      run: pwd

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Print working directory after CMake setup
      run: pwd

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglew-dev libglfw3-dev libglm-dev gfortran freeglut3-dev
        pwd

    - name: Build Google Test
      run: |
        mkdir -p build/googletest
        cd build/googletest
        pwd
        cmake ../../extern/googletest
        cmake --build .

    - name: Configure CMake
      run: cmake -S . -B build
      working-directory: .

    - name: Print working directory after configuring CMake
      run: pwd
      working-directory: .

    - name: Build
      run: cmake --build build --config Release
      working-directory: .

    - name: Run tests
      run: |
        cd build
        pwd
        ctest --output-on-failure
      working-directory: .
